services:
  db:
    image: postgres:15
    container_name: what_to_wear_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: what_to_wear
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: what_to_wear_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://user:password@db:5432/what_to_wear
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
