name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      WEATHER_API_BASE_URL: "https://mock_weatherapi.com/v1"
      WEATHER_API_KEY: "mock_api_key"
      DATABASE_URL: "sqlite:///test.db"
      LLM_API_URL: "https://mock_llm_api.com/v1"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Verify Environment Variables
        run: echo "WEATHER_API_BASE_URL=$WEATHER_API_BASE_URL"

      - name: Run Tests
        run: poetry run pytest --maxfail=1 --disable-warnings --cov=.
